apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBQrKuVg0U2Oebbls+jo6VhD6r9m+zIuZ83I/A91a6TOutTEWrY08hBr7/Iqm5IWHmPH53erlFbmXPFPyX9aNezKyLfHi6MyyZqNCaj49Kpf1uv0L9X/S6YcJEZkY03/3jD24Dbf30QhYvz2bjVVIHeQm9QxaEfQ46kVFOxWbPm7wg6PWNweEGyACVYfg16c1V5rNf2TJ0pvorjzXfF7gN6exBSr9NC2SGfl/Lq+p/GrQ4oTujajQJmmDCEh0AF237T8bKtMadizWWjG20fOq2COhDjrNTMSKIshwYOWDu4GtcVWWEcuTsU5idK6Du8OzbO9HI8++rO3c4Y211c/OwW+fZmmBK8UaMXDAoRQkj76Lh44AI2A2LnZZrm26nWYbBlqYfOEqIfBoeyiVH2Eg1BZWvQEZEaq6RowgSv3w1tqmk5Ch2463fG8fvoqs3e8I3VSssxdW4Kbo8OpVA+8t1PFYKt0gJSoAzlqMdjpI9eGnvk9iSHoyqiTiPM6bYXzUJP2FN7p2E3PzA61R0sRxAHGNt35XJo20d0Elp5kF8FbtScaWiWZyMj4NbTnyQdbV5jv8hgHRou9aUzniHTz9kJ8njMN1H8ix11pxccGYHTPVOL49TFVPPWwYzd2pu0HAmIWsxt6QEO0H5X4n3e3GiDm5vKZsA6UFWk4JyjrpFFxQr27rsSZ6Uqp8iQVUOPoOskKJKTgFIDxg==
    DB_USER: AgCs3DYyMwWCfIrD7TLG0xzMkUBN4JE+JjStCMyq6Coe5mhTYQnA5I+vTyvYp0gVqR0w9QSA3rkUUNy9w3NCrdyjX6FNdr5F//qcVlXl2aEdtXD5KhlVJ5lBAlGvt6SCPqQCmAFKa2qYdgt6F5/xu+0PC2kGsSwkTvy5q4x1aTREFSt3LEpPMDD5zzdyDAhKqAWs76YICdTzIj69coKZt6WrZ5DWvQXG2IoXKxBlAx6AUltZVS9ZMwiMN6ZCncDbCfiTDMZ1ZOEycFq2Xoe+hYpUvHMefRQQLP0M13H5YbtmqwdghWuwXEHodtUAn1uernNla80MxpO0jwha5XF67bNoRWcnftLeUeXtnC+aMPKAol36ub+ffU4pI4+FQrmhqvLlecA2SgiDL+VCB1PhPaRkOHhKmoewIl2+kCzKq5chF4T6tDzs1xV6W1IOSNbi9XAoRjRWIofctZAcYDvnxOnGo1CFrAVIOYvsfJuQ+dMW9JUZlHNjaboZR+DlPlarHWrmDxw5FjmZRLi1DK1Jn4drfMvPP8OTVGhLAgY/gL8gH0yn0gaBFDF15RllzeGIeFWSTzdb9J0BEvxd+USALv8fhNJHq4y/YKHspGVXLe6+Uu+CATFeUJgIpoC04q5sC9i+lO0Zmz6GyQNSKe1QLtsU6Ld62cr262SbzBb6ddAS9Zs4+h4kwgEv0bJqQN3EPvKLmGjijUvueQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

